site_name: 'Open Medical Datasets'
site_description: 'A website focused on collecting all the medical websites into one place.'
site_author: 'RawaaRajab'

repo_url: https://github.com/RawaaMoh

theme:
    name: null
    custom_dir: theme
    # default from mkdocs_theme.yml
    static_templates:
        - 404.html
    include_search_page: true
    search_index_only: true
    history_buttons: true
    article_nav_top: true
    article_nav_bottom: true

nav:
    - About: index.md
    # - Customization: customization.md
    - Websites:
        - General datasets: General.md
        - Sepecific datasets:
            - EEG: EEG.md
            - EMG: EMG.md
            - ECG: ECG.md
            - MRI: MRI.md
        # - Sample Page A: sample-a.md
        # - Sample Subfolder:
        #     - Sample Subpage A1: sample-a1.md
        #     - Sample Subpage A2: sample-a2.md
        # - Sample Page B: sample-b.md

markdown_extensions:
    - toc:
        permalink: '#'

extra:
    version: 0.0.2
