site_name: 'Open Medical Datasets'
site_description: 'A website focused on collecting all the medical websites into one place.'
site_author: 'RawaaRajab'

repo_url: https://github.com/RawaaMoh/OpenMedicalDatasets

theme:
    name: null
    custom_dir: theme
    # default from mkdocs_theme.yml
    static_templates:
        - 404.html
    include_search_page: true
    search_index_only: true
    history_buttons: true
    article_nav_top: true
    article_nav_bottom: true

nav:
    - About: index.md
    - Medical datasets: General.md
    - Signal related datasets:
        - EEG: EEG.md
        - EMG: EMG.md
        - ECG: ECG.md
    - Image related datasets:
        - MRI: MRI.md

markdown_extensions:
    - toc:
        permalink: '#'

extra:
    version: 03-2021
